version: '3.8'

services:
  postgres_db:
    container_name: 'app_db'
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5400:5432'
